// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package demo.proxies;

public class GankImage
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject gankImageMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Demo.GankImage";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		image("image"),
		GankImage_Gank("Demo.GankImage_Gank");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public GankImage(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "Demo.GankImage"));
	}

	protected GankImage(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject gankImageMendixObject)
	{
		if (gankImageMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("Demo.GankImage", gankImageMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a Demo.GankImage");

		this.gankImageMendixObject = gankImageMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'GankImage.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static demo.proxies.GankImage initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return demo.proxies.GankImage.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static demo.proxies.GankImage initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new demo.proxies.GankImage(context, mendixObject);
	}

	public static demo.proxies.GankImage load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return demo.proxies.GankImage.initialize(context, mendixObject);
	}

	public static java.util.List<demo.proxies.GankImage> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<demo.proxies.GankImage> result = new java.util.ArrayList<demo.proxies.GankImage>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//Demo.GankImage" + xpathConstraint))
			result.add(demo.proxies.GankImage.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of image
	 */
	public final java.lang.String getimage()
	{
		return getimage(getContext());
	}

	/**
	 * @param context
	 * @return value of image
	 */
	public final java.lang.String getimage(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.image.toString());
	}

	/**
	 * Set value of image
	 * @param image
	 */
	public final void setimage(java.lang.String image)
	{
		setimage(getContext(), image);
	}

	/**
	 * Set value of image
	 * @param context
	 * @param image
	 */
	public final void setimage(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String image)
	{
		getMendixObject().setValue(context, MemberNames.image.toString(), image);
	}

	/**
	 * @return value of GankImage_Gank
	 */
	public final demo.proxies.Gank getGankImage_Gank() throws com.mendix.core.CoreException
	{
		return getGankImage_Gank(getContext());
	}

	/**
	 * @param context
	 * @return value of GankImage_Gank
	 */
	public final demo.proxies.Gank getGankImage_Gank(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		demo.proxies.Gank result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.GankImage_Gank.toString());
		if (identifier != null)
			result = demo.proxies.Gank.load(context, identifier);
		return result;
	}

	/**
	 * Set value of GankImage_Gank
	 * @param gankimage_gank
	 */
	public final void setGankImage_Gank(demo.proxies.Gank gankimage_gank)
	{
		setGankImage_Gank(getContext(), gankimage_gank);
	}

	/**
	 * Set value of GankImage_Gank
	 * @param context
	 * @param gankimage_gank
	 */
	public final void setGankImage_Gank(com.mendix.systemwideinterfaces.core.IContext context, demo.proxies.Gank gankimage_gank)
	{
		if (gankimage_gank == null)
			getMendixObject().setValue(context, MemberNames.GankImage_Gank.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.GankImage_Gank.toString(), gankimage_gank.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return gankImageMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final demo.proxies.GankImage that = (demo.proxies.GankImage) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "Demo.GankImage";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
