// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package demo.proxies;

public class GanksImages
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject ganksImagesMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Demo.GanksImages";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Images_JsonObject("Demo.Images_JsonObject");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public GanksImages(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "Demo.GanksImages"));
	}

	protected GanksImages(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject ganksImagesMendixObject)
	{
		if (ganksImagesMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("Demo.GanksImages", ganksImagesMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a Demo.GanksImages");

		this.ganksImagesMendixObject = ganksImagesMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'GanksImages.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static demo.proxies.GanksImages initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return demo.proxies.GanksImages.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static demo.proxies.GanksImages initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new demo.proxies.GanksImages(context, mendixObject);
	}

	public static demo.proxies.GanksImages load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return demo.proxies.GanksImages.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Images_JsonObject
	 */
	public final demo.proxies.JsonObject getImages_JsonObject() throws com.mendix.core.CoreException
	{
		return getImages_JsonObject(getContext());
	}

	/**
	 * @param context
	 * @return value of Images_JsonObject
	 */
	public final demo.proxies.JsonObject getImages_JsonObject(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		demo.proxies.JsonObject result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Images_JsonObject.toString());
		if (identifier != null)
			result = demo.proxies.JsonObject.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Images_JsonObject
	 * @param images_jsonobject
	 */
	public final void setImages_JsonObject(demo.proxies.JsonObject images_jsonobject)
	{
		setImages_JsonObject(getContext(), images_jsonobject);
	}

	/**
	 * Set value of Images_JsonObject
	 * @param context
	 * @param images_jsonobject
	 */
	public final void setImages_JsonObject(com.mendix.systemwideinterfaces.core.IContext context, demo.proxies.JsonObject images_jsonobject)
	{
		if (images_jsonobject == null)
			getMendixObject().setValue(context, MemberNames.Images_JsonObject.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Images_JsonObject.toString(), images_jsonobject.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return ganksImagesMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final demo.proxies.GanksImages that = (demo.proxies.GanksImages) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "Demo.GanksImages";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
