// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package demo.proxies;

public class JsonObject
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject jsonObjectMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Demo.JsonObject";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		_id("_id"),
		CreatedAt("CreatedAt"),
		Desc("Desc"),
		PublishedAt("PublishedAt"),
		Source("Source"),
		_type("_type"),
		Url("Url"),
		Used("Used"),
		Who("Who"),
		JsonObject_Results("Demo.JsonObject_Results");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public JsonObject(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "Demo.JsonObject"));
	}

	protected JsonObject(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject jsonObjectMendixObject)
	{
		if (jsonObjectMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("Demo.JsonObject", jsonObjectMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a Demo.JsonObject");

		this.jsonObjectMendixObject = jsonObjectMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'JsonObject.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static demo.proxies.JsonObject initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return demo.proxies.JsonObject.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static demo.proxies.JsonObject initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new demo.proxies.JsonObject(context, mendixObject);
	}

	public static demo.proxies.JsonObject load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return demo.proxies.JsonObject.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of _id
	 */
	public final java.lang.String get_id()
	{
		return get_id(getContext());
	}

	/**
	 * @param context
	 * @return value of _id
	 */
	public final java.lang.String get_id(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames._id.toString());
	}

	/**
	 * Set value of _id
	 * @param _id
	 */
	public final void set_id(java.lang.String _id)
	{
		set_id(getContext(), _id);
	}

	/**
	 * Set value of _id
	 * @param context
	 * @param _id
	 */
	public final void set_id(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String _id)
	{
		getMendixObject().setValue(context, MemberNames._id.toString(), _id);
	}

	/**
	 * @return value of CreatedAt
	 */
	public final java.util.Date getCreatedAt()
	{
		return getCreatedAt(getContext());
	}

	/**
	 * @param context
	 * @return value of CreatedAt
	 */
	public final java.util.Date getCreatedAt(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.CreatedAt.toString());
	}

	/**
	 * Set value of CreatedAt
	 * @param createdat
	 */
	public final void setCreatedAt(java.util.Date createdat)
	{
		setCreatedAt(getContext(), createdat);
	}

	/**
	 * Set value of CreatedAt
	 * @param context
	 * @param createdat
	 */
	public final void setCreatedAt(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date createdat)
	{
		getMendixObject().setValue(context, MemberNames.CreatedAt.toString(), createdat);
	}

	/**
	 * @return value of Desc
	 */
	public final java.lang.String getDesc()
	{
		return getDesc(getContext());
	}

	/**
	 * @param context
	 * @return value of Desc
	 */
	public final java.lang.String getDesc(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Desc.toString());
	}

	/**
	 * Set value of Desc
	 * @param desc
	 */
	public final void setDesc(java.lang.String desc)
	{
		setDesc(getContext(), desc);
	}

	/**
	 * Set value of Desc
	 * @param context
	 * @param desc
	 */
	public final void setDesc(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String desc)
	{
		getMendixObject().setValue(context, MemberNames.Desc.toString(), desc);
	}

	/**
	 * @return value of PublishedAt
	 */
	public final java.util.Date getPublishedAt()
	{
		return getPublishedAt(getContext());
	}

	/**
	 * @param context
	 * @return value of PublishedAt
	 */
	public final java.util.Date getPublishedAt(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.PublishedAt.toString());
	}

	/**
	 * Set value of PublishedAt
	 * @param publishedat
	 */
	public final void setPublishedAt(java.util.Date publishedat)
	{
		setPublishedAt(getContext(), publishedat);
	}

	/**
	 * Set value of PublishedAt
	 * @param context
	 * @param publishedat
	 */
	public final void setPublishedAt(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date publishedat)
	{
		getMendixObject().setValue(context, MemberNames.PublishedAt.toString(), publishedat);
	}

	/**
	 * @return value of Source
	 */
	public final java.lang.String getSource()
	{
		return getSource(getContext());
	}

	/**
	 * @param context
	 * @return value of Source
	 */
	public final java.lang.String getSource(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Source.toString());
	}

	/**
	 * Set value of Source
	 * @param source
	 */
	public final void setSource(java.lang.String source)
	{
		setSource(getContext(), source);
	}

	/**
	 * Set value of Source
	 * @param context
	 * @param source
	 */
	public final void setSource(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String source)
	{
		getMendixObject().setValue(context, MemberNames.Source.toString(), source);
	}

	/**
	 * @return value of _type
	 */
	public final java.lang.String get_type()
	{
		return get_type(getContext());
	}

	/**
	 * @param context
	 * @return value of _type
	 */
	public final java.lang.String get_type(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames._type.toString());
	}

	/**
	 * Set value of _type
	 * @param _type
	 */
	public final void set_type(java.lang.String _type)
	{
		set_type(getContext(), _type);
	}

	/**
	 * Set value of _type
	 * @param context
	 * @param _type
	 */
	public final void set_type(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String _type)
	{
		getMendixObject().setValue(context, MemberNames._type.toString(), _type);
	}

	/**
	 * @return value of Url
	 */
	public final java.lang.String getUrl()
	{
		return getUrl(getContext());
	}

	/**
	 * @param context
	 * @return value of Url
	 */
	public final java.lang.String getUrl(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Url.toString());
	}

	/**
	 * Set value of Url
	 * @param url
	 */
	public final void setUrl(java.lang.String url)
	{
		setUrl(getContext(), url);
	}

	/**
	 * Set value of Url
	 * @param context
	 * @param url
	 */
	public final void setUrl(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String url)
	{
		getMendixObject().setValue(context, MemberNames.Url.toString(), url);
	}

	/**
	 * @return value of Used
	 */
	public final java.lang.Boolean getUsed()
	{
		return getUsed(getContext());
	}

	/**
	 * @param context
	 * @return value of Used
	 */
	public final java.lang.Boolean getUsed(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Used.toString());
	}

	/**
	 * Set value of Used
	 * @param used
	 */
	public final void setUsed(java.lang.Boolean used)
	{
		setUsed(getContext(), used);
	}

	/**
	 * Set value of Used
	 * @param context
	 * @param used
	 */
	public final void setUsed(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean used)
	{
		getMendixObject().setValue(context, MemberNames.Used.toString(), used);
	}

	/**
	 * @return value of Who
	 */
	public final java.lang.String getWho()
	{
		return getWho(getContext());
	}

	/**
	 * @param context
	 * @return value of Who
	 */
	public final java.lang.String getWho(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Who.toString());
	}

	/**
	 * Set value of Who
	 * @param who
	 */
	public final void setWho(java.lang.String who)
	{
		setWho(getContext(), who);
	}

	/**
	 * Set value of Who
	 * @param context
	 * @param who
	 */
	public final void setWho(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String who)
	{
		getMendixObject().setValue(context, MemberNames.Who.toString(), who);
	}

	/**
	 * @return value of JsonObject_Results
	 */
	public final demo.proxies.Results getJsonObject_Results() throws com.mendix.core.CoreException
	{
		return getJsonObject_Results(getContext());
	}

	/**
	 * @param context
	 * @return value of JsonObject_Results
	 */
	public final demo.proxies.Results getJsonObject_Results(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		demo.proxies.Results result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.JsonObject_Results.toString());
		if (identifier != null)
			result = demo.proxies.Results.load(context, identifier);
		return result;
	}

	/**
	 * Set value of JsonObject_Results
	 * @param jsonobject_results
	 */
	public final void setJsonObject_Results(demo.proxies.Results jsonobject_results)
	{
		setJsonObject_Results(getContext(), jsonobject_results);
	}

	/**
	 * Set value of JsonObject_Results
	 * @param context
	 * @param jsonobject_results
	 */
	public final void setJsonObject_Results(com.mendix.systemwideinterfaces.core.IContext context, demo.proxies.Results jsonobject_results)
	{
		if (jsonobject_results == null)
			getMendixObject().setValue(context, MemberNames.JsonObject_Results.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.JsonObject_Results.toString(), jsonobject_results.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return jsonObjectMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final demo.proxies.JsonObject that = (demo.proxies.JsonObject) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "Demo.JsonObject";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
