// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package demo.proxies;

public class Pages
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject pagesMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Demo.Pages";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		GetType("GetType"),
		pageSize("pageSize"),
		nowPage("nowPage");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Pages(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "Demo.Pages"));
	}

	protected Pages(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject pagesMendixObject)
	{
		if (pagesMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("Demo.Pages", pagesMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a Demo.Pages");

		this.pagesMendixObject = pagesMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Pages.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static demo.proxies.Pages initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return demo.proxies.Pages.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static demo.proxies.Pages initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new demo.proxies.Pages(context, mendixObject);
	}

	public static demo.proxies.Pages load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return demo.proxies.Pages.initialize(context, mendixObject);
	}

	public static java.util.List<demo.proxies.Pages> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<demo.proxies.Pages> result = new java.util.ArrayList<demo.proxies.Pages>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//Demo.Pages" + xpathConstraint))
			result.add(demo.proxies.Pages.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * Set value of GetType
	 * @param gettype
	 */
	public final demo.proxies.SourceType getGetType()
	{
		return getGetType(getContext());
	}

	/**
	 * @param context
	 * @return value of GetType
	 */
	public final demo.proxies.SourceType getGetType(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.GetType.toString());
		if (obj == null)
			return null;

		return demo.proxies.SourceType.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of GetType
	 * @param gettype
	 */
	public final void setGetType(demo.proxies.SourceType gettype)
	{
		setGetType(getContext(), gettype);
	}

	/**
	 * Set value of GetType
	 * @param context
	 * @param gettype
	 */
	public final void setGetType(com.mendix.systemwideinterfaces.core.IContext context, demo.proxies.SourceType gettype)
	{
		if (gettype != null)
			getMendixObject().setValue(context, MemberNames.GetType.toString(), gettype.toString());
		else
			getMendixObject().setValue(context, MemberNames.GetType.toString(), null);
	}

	/**
	 * @return value of pageSize
	 */
	public final java.lang.Integer getpageSize()
	{
		return getpageSize(getContext());
	}

	/**
	 * @param context
	 * @return value of pageSize
	 */
	public final java.lang.Integer getpageSize(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.pageSize.toString());
	}

	/**
	 * Set value of pageSize
	 * @param pagesize
	 */
	public final void setpageSize(java.lang.Integer pagesize)
	{
		setpageSize(getContext(), pagesize);
	}

	/**
	 * Set value of pageSize
	 * @param context
	 * @param pagesize
	 */
	public final void setpageSize(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer pagesize)
	{
		getMendixObject().setValue(context, MemberNames.pageSize.toString(), pagesize);
	}

	/**
	 * @return value of nowPage
	 */
	public final java.lang.Long getnowPage()
	{
		return getnowPage(getContext());
	}

	/**
	 * @param context
	 * @return value of nowPage
	 */
	public final java.lang.Long getnowPage(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.nowPage.toString());
	}

	/**
	 * Set value of nowPage
	 * @param nowpage
	 */
	public final void setnowPage(java.lang.Long nowpage)
	{
		setnowPage(getContext(), nowpage);
	}

	/**
	 * Set value of nowPage
	 * @param context
	 * @param nowpage
	 */
	public final void setnowPage(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long nowpage)
	{
		getMendixObject().setValue(context, MemberNames.nowPage.toString(), nowpage);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return pagesMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final demo.proxies.Pages that = (demo.proxies.Pages) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "Demo.Pages";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
