// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package widgets.proxies;

public class StringParam
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject stringParamMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Widgets.StringParam";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		param("param");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public StringParam(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "Widgets.StringParam"));
	}

	protected StringParam(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject stringParamMendixObject)
	{
		if (stringParamMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("Widgets.StringParam", stringParamMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a Widgets.StringParam");

		this.stringParamMendixObject = stringParamMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'StringParam.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static widgets.proxies.StringParam initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return widgets.proxies.StringParam.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static widgets.proxies.StringParam initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new widgets.proxies.StringParam(context, mendixObject);
	}

	public static widgets.proxies.StringParam load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return widgets.proxies.StringParam.initialize(context, mendixObject);
	}

	public static java.util.List<widgets.proxies.StringParam> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<widgets.proxies.StringParam> result = new java.util.ArrayList<widgets.proxies.StringParam>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//Widgets.StringParam" + xpathConstraint))
			result.add(widgets.proxies.StringParam.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of param
	 */
	public final java.lang.String getparam()
	{
		return getparam(getContext());
	}

	/**
	 * @param context
	 * @return value of param
	 */
	public final java.lang.String getparam(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.param.toString());
	}

	/**
	 * Set value of param
	 * @param param
	 */
	public final void setparam(java.lang.String param)
	{
		setparam(getContext(), param);
	}

	/**
	 * Set value of param
	 * @param context
	 * @param param
	 */
	public final void setparam(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String param)
	{
		getMendixObject().setValue(context, MemberNames.param.toString(), param);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return stringParamMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final widgets.proxies.StringParam that = (widgets.proxies.StringParam) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "Widgets.StringParam";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
