// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package demo.actions;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import demo.proxies.User;

public class AddDataDemo extends CustomJavaAction<IMendixObject>
{
	private java.lang.String UserName;
	private java.lang.String Password;
	private java.lang.Long Age;

	public AddDataDemo(IContext context, java.lang.String UserName, java.lang.String Password, java.lang.Long Age)
	{
		super(context);
		this.UserName = UserName;
		this.Password = Password;
		this.Age = Age;
	}

	@Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE
	//第一种方式使用 IMendxObject创建数据		
	// IMendixObject ob=	Core.instantiate(getContext(),"Demo.User");
	// ob.setValue(getContext(),"UserName",UserName);
	// ob.setValue(getContext(),"Password",Password);
	// ob.setValue(getContext(),"Age",Age);
	// Core.commit(getContext(),ob);

	//第二种方式直接创建对象
	User us=new User(getContext());
	us.setUserName(UserName);
	us.setPassword(Password);
	us.setAge(Age);
	//提交数据到数据库
	us.commit(getContext());
	//也可以使用以下方式
	//Core.commit(getContext(),us.getMendixObject());
	return us.getMendixObject();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public java.lang.String toString()
	{
		return "AddDataDemo";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
