// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package demo.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import demo.proxies.User;
import com.mendix.core.Core;
import java.util.HashMap;
import java.util.Map;

public class ExecuteMFDemo extends CustomJavaAction<java.lang.String>
{
	private java.lang.String mf;
	private IMendixObject __ParameterParameter1;
	private demo.proxies.User ParameterParameter1;
	private java.lang.String other;

	public ExecuteMFDemo(IContext context, java.lang.String mf, IMendixObject ParameterParameter1, java.lang.String other)
	{
		super(context);
		this.mf = mf;
		this.__ParameterParameter1 = ParameterParameter1;
		this.other = other;
	}

	@Override
	public java.lang.String executeAction() throws Exception
	{
		this.ParameterParameter1 = __ParameterParameter1 == null ? null : demo.proxies.User.initialize(getContext(), __ParameterParameter1);

		// BEGIN USER CODE
		Map<String,Object> map=new HashMap<>();
		//记得转换成mendixobject,且Map的key需要和微流入参的名称一样
		map.put("User",ParameterParameter1.getMendixObject());
		map.put("other",other);
		//执行微流，mf为微流，map则为需要执行微流的入参
		String result=Core.execute(getContext(),mf,map);
		return result;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public java.lang.String toString()
	{
		return "ExecuteMFDemo";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
