// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package demo.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import javax.servlet.http.Cookie;

public class GetCookies extends CustomJavaAction<java.lang.String>
{
	public GetCookies(IContext context)
	{
		super(context);
	}

	@Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
		//throw new com.mendix.systemwideinterfaces.MendixRuntimeException("Java action was not implemented");
		String cookies="";
		Cookie[] cook=this.context().getRuntimeRequest().get().getHttpServletRequest().getCookies();

		for(Cookie c:cook){
			cookies+=c.getName()+"="+c.getValue()+";";
		}
		return  cookies;

		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public java.lang.String toString()
	{
		return "GetCookies";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
