// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package demo.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import demo.proxies.User;
import com.mendix.core.Core;

public class ModifyDataDemo extends CustomJavaAction<IMendixObject>
{
	private IMendixObject __ParameterParameter1;
	private demo.proxies.User ParameterParameter1;

	public ModifyDataDemo(IContext context, IMendixObject ParameterParameter1)
	{
		super(context);
		this.__ParameterParameter1 = ParameterParameter1;
	}

	@Override
	public IMendixObject executeAction() throws Exception
	{
		this.ParameterParameter1 = __ParameterParameter1 == null ? null : demo.proxies.User.initialize(getContext(), __ParameterParameter1);

		// BEGIN USER CODE
		ParameterParameter1.setUserName("===>我修改啦");
		ParameterParameter1.setPassword("我修改了密码");
		ParameterParameter1.setAge(200L);
		Core.commit(getContext(),ParameterParameter1.getMendixObject());
		return ParameterParameter1.getMendixObject();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public java.lang.String toString()
	{
		return "ModifyDataDemo";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
