// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package processqueue.actions;

import com.mendix.systemwideinterfaces.core.IMendixObject;
import processqueue.queuehandler.QueueHandler;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;

/**
 * Initialize the Queue using all configuration options specified in the entity. 
 * This prepares the Queue so actions can be added.
 */
public class InitializeQueue extends CustomJavaAction<java.lang.Boolean>
{
	private IMendixObject QueConfig;

	public InitializeQueue(IContext context, IMendixObject QueConfig)
	{
		super(context);
		this.QueConfig = QueConfig;
	}

	@Override
	public java.lang.Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
		QueueHandler.getQueueHandler().initializeQueue(getContext(), this.QueConfig);
		return true;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public java.lang.String toString()
	{
		return "InitializeQueue";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
